### ISSUE TITLE
EVENT HANDLER:  Favorite Click

### ISSUE THREAD

**Issue by bfall-debug** [bfall-debug/project_1#8]
Create event handler that triggers when star on  concert card is  is clicked that saves the concert information to localstorage.

the information should be an object that is appended to an array of all the bands

**Comment by rachaelchar** [comment]
Sorry for all the moving around on this issue. The button will currently save a static object called showInfo that has generic properties, and I am working on getting it to save the information for the event that the user is favoriting.
